name: Identificar proyectos Cloudflare Pages

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/list-cloudflare-pages.yml

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - name: Listar proyectos disponibles
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project list
